dist: trusty
sudo: false
language: elixir
elixir:
  - 1.9
otp_release:
  - 22.0
addons:
  postgresql: '9.6'
  apt:
    packages:
      - postgresql-9.6-postgis-2.4
services:
  - postgresql
before_script:
  - psql -c 'create database geo_postgrex_test;' -U postgres
  - psql -c 'create extension postgis;' -U postgres -d geo_postgrex_test
  - psql -d postgres -c "alter extension postgis update to "2.4";
script:
  - mix test
before_deploy:
  - mix compile
deploy:
  skip_cleanup: true
  provider: script
  script: mix hex.publish --yes
  on:
    tags: true
