dist: trusty
sudo: false
language: elixir
elixir:
  - 1.4.5
  - 1.5.3
  - 1.6.0
otp_release:
  - 19.0
  - 20.0
addons:
  postgresql: '9.6'
  apt:
    packages:
      - postgresql-9.6-postgis-2.3
services:
  - postgresql
before_script:
  - psql -c 'create database geo_postgrex_test;' -U postgres
  - psql -c 'create extension postgis;' -U postgres -d geo_postgrex_test
